#开发配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/elites?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: sa
    password: qwe!23
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    password: 12345
    #连接超时时间（毫秒）
    timeout: 3600s

#公共配置与profiles选择无关
mybatis:
   typeAliasesPackage: com.entity
  #mapperLocations: classpath:mapper/*.xml
